// <auto-generated />
using System;
using CampingLaRustique.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampingLaRustique.Migrations
{
    [DbContext(typeof(KlantenContext))]
    [Migration("20210203000648_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CampingLaRustique.Models.Camping", b =>
                {
                    b.Property<int>("PlekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Elektriciteit")
                        .HasColumnType("bit");

                    b.Property<bool>("GratisDouche")
                        .HasColumnType("bit");

                    b.Property<bool>("Huisdieren")
                        .HasColumnType("bit");

                    b.Property<string>("Ligging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oppervlakte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlekID");

                    b.ToTable("Camping");
                });

            modelBuilder.Entity("CampingLaRustique.Models.Klanten", b =>
                {
                    b.Property<int>("KlantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Achternaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlantID");

                    b.ToTable("Klant");
                });

            modelBuilder.Entity("CampingLaRustique.Models.Reservering", b =>
                {
                    b.Property<int>("Reserveringsnummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Betaald")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlantID")
                        .HasColumnType("int");

                    b.Property<int>("PlekID")
                        .HasColumnType("int");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Reserveringsnummer");

                    b.ToTable("Reservering");
                });
#pragma warning restore 612, 618
        }
    }
}
